services:
  mysql-master:  # Master
    image: mysql:8.3  # MySQL 버전 8.3으로 명시
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: settlementdb
    ports:
      - "3306:3306"
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-do-db=settlementdb
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    volumes:
      - master_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql-slave:  # Slave
    image: mysql:8.3  # MySQL 버전 8.3으로 명시
    container_name: mysql-slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: settlementdb
    ports:
      - "3307:3306"
    command: >
      --server-id=2
      --relay-log=mysql-relay-bin
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --replicate-do-db=settlementdb
    depends_on:
      mysql-master:
        condition: service_healthy
    volumes:
      - slave_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  settlement-service:
    image: openjdk:17-jdk-slim
    container_name: settlement-service
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: settlement-service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-master:3306/settlementdb
      SPRING_DATASOURCE_SLAVE_URL: jdbc:mysql://mysql-slave:3306/settlementdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: manager
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS: true
      SPRING_BATCH_JOB_ENABLED: false
      SPRING_BATCH_JDBC_INITIALIZE_SCHEMA: always
      SPRING_BATCH_JDBC_SCHEMA: classpath:org/springframework/batch/core/schema-mysql.sql
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CACHE: trace
      SPRING_CONFIG_LOCATION: classpath:/application-docker.yml
    volumes:
      - ./build/libs/settlement-service-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: ["java", "-jar", "app.jar"]
    depends_on:
      mysql-master:
        condition: service_healthy
      mysql-slave:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  master_data:
  slave_data:
