spring:
  application:
    name: settlement-service

  datasource:
    url: jdbc:mysql://localhost:3306/settlementdb
    username: root
    password: manager
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: y2CBN5vgen8wv2O2n_wf
            client-secret: 4CmlmcBxgu
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          google:
            client-name: google
            client-id: 1079304204618-m7q03mqm24evnrrdtj9b9l4etvnq2hud.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.cache: trace # Redis 관련 로깅 레벨 설정
