spring:
  application:
    name: settlement-service

  datasource:
    master:
      jdbc-url: jdbc:mysql://mysql-master:3306/settlementdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      username: root
      password: manager
      driver-class-name: com.mysql.cj.jdbc.Driver
#      hikari:
#        maximum-pool-size: 30  # 마스터 커넥션 풀 30개  , 설정이 안먹히는 관계로 db config에 pool사이즈 작성

    slave:
      jdbc-url: jdbc:mysql://mysql-slave:3306/settlementdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      username: root
      password: manager
      driver-class-name: com.mysql.cj.jdbc.Driver
#      hikari:
#        maximum-pool-size: 30  # 슬레이브 커넥션 풀 30개
  data:
    redis:
      host: redis
      port: 6379

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: y2CBN5vgen8wv2O2n_wf
            client-secret: 4CmlmcBxgu
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-name: google
            client-id: 1079304204618-m7q03mqm24evnrrdtj9b9l4etvnq2hud.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  secret: ${JWT_SECRET:MySuperSecureJwtSecretKey123456!}

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.cache: trace  #  HikariCP 디버그 로그 활성화 추가